#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-julia =						\
	papers/julia/packages.tex					\
	papers/julia/main.tex					\
	papers/julia/references.bib				\
	papers/julia/teil0.tex					\
	papers/julia/teil1.tex					\
	papers/julia/teil2.tex					\
	papers/julia/teil3.tex

