#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-produkt =						\
	papers/produkt/packages.tex					\
	papers/produkt/main.tex					\
	papers/produkt/references.bib				\
	papers/produkt/teil0.tex					\
	papers/produkt/teil1.tex					\
	papers/produkt/teil2.tex					\
	papers/produkt/teil3.tex

