#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-pade =						\
	papers/pade/packages.tex					\
	papers/pade/main.tex					\
	papers/pade/references.bib				\
	papers/pade/teil0.tex					\
	papers/pade/teil1.tex					\
	papers/pade/teil2.tex					\
	papers/pade/teil3.tex

