#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-elektro =						\
	papers/elektro/packages.tex					\
	papers/elektro/main.tex					\
	papers/elektro/references.bib				\
	papers/elektro/teil0.tex					\
	papers/elektro/teil1.tex					\
	papers/elektro/teil2.tex					\
	papers/elektro/teil3.tex

