#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-basel =						\
	papers/basel/packages.tex					\
	papers/basel/main.tex					\
	papers/basel/references.bib				\
	papers/basel/teil0.tex					\
	papers/basel/teil1.tex					\
	papers/basel/teil2.tex					\
	papers/basel/teil3.tex

