#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kepler =						\
	papers/kepler/packages.tex					\
	papers/kepler/main.tex					\
	papers/kepler/references.bib				\
	papers/kepler/teil0.tex					\
	papers/kepler/teil1.tex					\
	papers/kepler/teil2.tex					\
	papers/kepler/teil3.tex

