#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-aircraft =						\
	papers/aircraft/packages.tex					\
	papers/aircraft/main.tex					\
	papers/aircraft/references.bib				\
	papers/aircraft/teil0.tex					\
	papers/aircraft/teil1.tex					\
	papers/aircraft/teil2.tex					\
	papers/aircraft/teil3.tex

