#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-jordan =						\
	papers/jordan/packages.tex					\
	papers/jordan/main.tex					\
	papers/jordan/references.bib				\
	papers/jordan/teil0.tex					\
	papers/jordan/teil1.tex					\
	papers/jordan/teil2.tex					\
	papers/jordan/teil3.tex

