#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-buchberger =						\
	papers/buchberger/packages.tex					\
	papers/buchberger/main.tex					\
	papers/buchberger/references.bib				\
	papers/buchberger/teil0.tex					\
	papers/buchberger/teil1.tex					\
	papers/buchberger/teil2.tex					\
	papers/buchberger/teil3.tex

