#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-venn =						\
	papers/venn/packages.tex					\
	papers/venn/main.tex					\
	papers/venn/references.bib				\
	papers/venn/teil0.tex					\
	papers/venn/teil1.tex					\
	papers/venn/teil2.tex					\
	papers/venn/teil3.tex

