#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-joukowski =						\
	papers/joukowski/packages.tex					\
	papers/joukowski/main.tex					\
	papers/joukowski/references.bib				\
	papers/joukowski/teil0.tex					\
	papers/joukowski/teil1.tex					\
	papers/joukowski/teil2.tex					\
	papers/joukowski/teil3.tex

