#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-laplace =						\
	papers/laplace/packages.tex					\
	papers/laplace/main.tex					\
	papers/laplace/references.bib				\
	papers/laplace/teil0.tex					\
	papers/laplace/teil1.tex					\
	papers/laplace/teil2.tex					\
	papers/laplace/teil3.tex

