#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-qa =						\
	papers/qa/packages.tex					\
	papers/qa/main.tex					\
	papers/qa/references.bib				\
	papers/qa/teil0.tex					\
	papers/qa/teil1.tex					\
	papers/qa/teil2.tex					\
	papers/qa/teil3.tex

