#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-gamma =						\
	papers/gamma/packages.tex					\
	papers/gamma/main.tex					\
	papers/gamma/references.bib				\
	papers/gamma/teil0.tex					\
	papers/gamma/teil1.tex					\
	papers/gamma/teil2.tex					\
	papers/gamma/teil3.tex

