#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-bessel =						\
	papers/bessel/packages.tex					\
	papers/bessel/main.tex					\
	papers/bessel/references.bib				\
	papers/bessel/teil0.tex					\
	papers/bessel/teil1.tex					\
	papers/bessel/teil2.tex					\
	papers/bessel/teil3.tex

