#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-weyl =						\
	papers/weyl/packages.tex					\
	papers/weyl/main.tex					\
	papers/weyl/references.bib				\
	papers/weyl/teil0.tex					\
	papers/weyl/teil1.tex					\
	papers/weyl/teil2.tex					\
	papers/weyl/teil3.tex

