#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-moebius =						\
	papers/moebius/packages.tex					\
	papers/moebius/main.tex					\
	papers/moebius/references.bib				\
	papers/moebius/teil0.tex					\
	papers/moebius/teil1.tex					\
	papers/moebius/teil2.tex					\
	papers/moebius/teil3.tex

