#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-step =						\
	papers/step/packages.tex					\
	papers/step/main.tex					\
	papers/step/references.bib				\
	papers/step/teil0.tex					\
	papers/step/teil1.tex					\
	papers/step/teil2.tex					\
	papers/step/teil3.tex

