#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/060-ratint/1-bernoulli.tex				\
	chapters/060-ratint/2-euklid.tex				\
	chapters/060-ratint/3-hermite.tex				\
	chapters/060-ratint/4-rothsteintrager.tex			\
	chapters/060-ratint/chapter.tex

