#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-hauptwert =						\
	papers/hauptwert/packages.tex					\
	papers/hauptwert/main.tex					\
	papers/hauptwert/references.bib				\
	papers/hauptwert/teil0.tex					\
	papers/hauptwert/teil1.tex					\
	papers/hauptwert/teil2.tex					\
	papers/hauptwert/teil3.tex

