include papers/aircraft/Makefile.inc
include papers/basel/Makefile.inc
include papers/beispiel/Makefile.inc
include papers/elektro/Makefile.inc
include papers/fresnel/Makefile.inc
include papers/jordan/Makefile.inc
include papers/joukowski/Makefile.inc
include papers/julia/Makefile.inc
include papers/kepler/Makefile.inc
include papers/laplace/Makefile.inc
include papers/produkt/Makefile.inc
include papers/qa/Makefile.inc
include papers/venn/Makefile.inc
include papers/weyl/Makefile.inc
include papers/zeta/Makefile.inc

TEXFILES = \
	$(dependencies-aircraft) \
	$(dependencies-basel) \
	$(dependencies-beispiel) \
	$(dependencies-elektro) \
	$(dependencies-fresnel) \
	$(dependencies-jordan) \
	$(dependencies-joukowski) \
	$(dependencies-julia) \
	$(dependencies-kepler) \
	$(dependencies-laplace) \
	$(dependencies-produkt) \
	$(dependencies-qa) \
	$(dependencies-venn) \
	$(dependencies-weyl) \
	$(dependencies-zeta) \

